fix for the building under CentOS 6
This fixes the following errors:
```
[root@ip-172-22-2-106 build]# scl enable rh-python36 -- ninja install
[1/30] Compiling C object 'example/passthrough_ll@exe/passthrough_ll.c.o'.
FAILED: example/passthrough_ll@exe/passthrough_ll.c.o
cc  -Iexample/passthrough_ll@exe -Iexample -I../example -I. -I../ -Ilib -I../lib -Iinclude -I../include -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O2 -g -D_REENTRANT -DHAVE_CONFIG_H -Wall -Wextra -Wno-sign-compare -Wstrict-prototypes -Wmissing-declarations -Wwrite-strings -fno-strict-aliasing -Wno-unused-result -MD -MQ 'example/passthrough_ll@exe/passthrough_ll.c.o' -MF 'example/passthrough_ll@exe/passthrough_ll.c.o.d' -o 'example/passthrough_ll@exe/passthrough_ll.c.o' -c ../example/passthrough_ll.c
../example/passthrough_ll.c: In function ‘lo_getattr’:
../example/passthrough_ll.c:136: error: ‘AT_EMPTY_PATH’ undeclared (first use in this function)
../example/passthrough_ll.c:136: error: (Each undeclared identifier is reported only once
../example/passthrough_ll.c:136: error: for each function it appears in.)
../example/passthrough_ll.c: In function ‘lo_do_lookup’:
../example/passthrough_ll.c:166: error: ‘O_PATH’ undeclared (first use in this function)
../example/passthrough_ll.c:170: error: ‘AT_EMPTY_PATH’ undeclared (first use in this function)
../example/passthrough_ll.c: In function ‘main’:
../example/passthrough_ll.c:572: error: ‘O_PATH’ undeclared (first use in this function)
At top level:
cc1: warning: unrecognized command line option "-Wno-unused-result"
[2/30] Compiling C object 'example/null@exe/null.c.o'.
ninja: build stopped: subcommand failed.
```