Fix build failure with uclibc
Building with uclibc leads to failure:
```
FAILED: lib/libfuse3.so.3.12.0.p/helper.c.o.
/home/giuliobenetti/git/upstream/test-libfuse3/bootlin-armv5-uclibc/host/bin/arm-linux-gcc -Ilib/libf
In file included from ../lib/fuse_i.h:10,
                 from ../lib/helper.c:14:
../include/fuse_lowlevel.h:1921:40: error: redefinition of ‘fuse_parse_cmdline_312’
 1921 | #define fuse_parse_cmdline(args, opts) fuse_parse_cmdline_312(args, opts)
      |                                        ^~~~~~~~~~~~~~~~~~~~~~
../lib/helper.c:258:5: note: in expansion of macro ‘fuse_parse_cmdline’
  258 | int fuse_parse_cmdline(struct fuse_args *args,
      |     ^~~~~~~~~~~~~~~~~~
../lib/helper.c:208:5: note: previous definition of ‘fuse_parse_cmdline_312’ was here
  208 | int fuse_parse_cmdline_312(struct fuse_args *args,
```
This happens because uclibc, depending on version, can support symver, so
if symver is supported and uclibc is used function fuse_parse_cmdline_312()
will be defined twice:
1. the function itself with symver
2. fuse_parse_cmdline() as the #define of fuse_parse_cmdline_312() and its
prototype
This leads to have the redefinition of ‘fuse_parse_cmdline_312’.

To solve this let's replace the 2 #define fuse_parse_cmdline() with static
functions in fuse_lowlevel.h and consequently remove the UCLIBC and APPLE
fuse_parse_cmdline() implementation from helper.c

Signed-off-by: Giulio Benetti <giulio.benetti@benettiengineering.com>