Fix build in musl libc
Function fuse_set_thread_name() assumes that pthread_t is an unsigned long
and fails to compile in musl libc with the following:

../lib/util.c: In function 'fuse_set_thread_name':
../lib/util.c:48:28: error: passing argument 1 of 'pthread_setname_np' makes \
        pointer from integer without a cast [-Wint-conversion]

Fix fuse_set_thread_name() by dropping the 'tid' parameter, as it is always
set to pthread_self().

Signed-off-by: Luis Henriques <luis@igalia.com>