Fix 'find_previous_release_tag.sh' if current version has no tag
For development it is expected that the current version doesn't have
a tag yet.

bernd@e7270 libfuse.git>.github/workflows/find_previous_release_tag.sh
Current version: 3.19.0-rc0
Current major.minor: 3.19
All major.minor versions found:
2.9
...
3.17
3.18
Error: No previous major.minor version found before 3.19

Signed-off-by: Bernd Schubert <bernd@bsbernd.com>